apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-predictor-deployment
  labels:
    app: rent-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent-predictor
  template:
    metadata:
      labels:
        app: rent-predictor
    spec:
      containers:
        - name: rent-predictor
          image: 522814708632.dkr.ecr.us-east-2.amazonaws.com/my-fastapi-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_REGION
            - name: PACKAGE_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: PACKAGE_NAME
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: S3_BUCKET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: rent-predictor-service
spec:
  selector:
    app: rent-predictor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
